server:
  port: 8086

spring:
  kafka:
    bootstrap-servers: 54.213.123.143:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: social-media-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:mysql://project6550.cluster-czaks8se8a2j.us-west-2.rds.amazonaws.com:3306/social_media?useSSL=false&serverTimezone=UTC
    username: admin
    password: yuxichen
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
